export const types = {
    // Sync
    SET_USER: "SET_USER",
    LOGOUT: "LOGOUT",
    INITIALIZED: "INITIALIZED",
    PROFILE_UPDATING: "PROFILE_UPDATING",
    PROFILE_UPDATED: "PROFILE_UPDATED",
    PROFILE_UPDATE_ERROR: "PROFILE_UPDATE_ERROR",
    PROFILE_UPDATE_RESET: "PROFILE_UPDATE_RESET",

    // Async    
    LOGIN_ASYNC: "LOGIN_ASYNC",
    LOGOUT_ASYNC: "LOGOUT_ASYNC",    
    UPDATE_PROFILE_ASYNC: "UPDATE_PROFILE_ASYNC",
};
