export const types = {
    // Sync
    SET_PRODUCTS: "SET_PRODUCTS",
    SET_PRODUCT: "SET_PRODUCT",    

    // Async    
    FETCH_PRODUCTS_ASYNC: "FETCH_PRODUCTS_ASYNC",
    FETCH_PRODUCT_ASYNC: "FETCH_PRODUCT_ASYNC",
};
