export const types = {
    // Sync
    SET_CATEGORIES: "SET_CATEGORIES",
    SET_CATEGORY: "SET_CATEGORY",
    SET_SELECTED_CATEGORY_ID: "SET_SELECTED_CATEGORY_ID",

    // Async    
    FETCH_CATEGORIES_ASYNC: "FETCH_CATEGORIES_ASYNC",
    FETCH_CATEGORY_ASYNC: "FETCH_CATEGORY_ASYNC",
};
